# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20171125_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
