# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_auto_20171128_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdID',
            new_name='imdbId',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tmdbID',
            new_name='tmdbId',
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.Movie'),
        ),
    ]
